hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

dataset_module:
  batch_size: 4
  num_workers: 2
  dataset_root: "path/to/dataset/root"
  use_all_augmentations: true
  resize_augmentation_keys: null
  augmentation_keys: null
  weights: 10

train_module:
  lr: 0.0001
  nn_input_image_resolution: 256
  latent_dim: 16
  hidden_dims: [32, 64, 128, 256, 512]
  recon_loss_weight: 10000.0
  kld_loss_weight: 1.0

training:
  wandb_project: "edge-aware-face-autoencoder"
  wandb_name: "test-run"
  with_gpu: false
  max_epochs: 10
  early_stop:
    monitor: "val_loss"
    patience: 5
    mode: "min"
